server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminGeneral-microservice
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
  instance:
    hostname: localhost