server:
  port: 8006
spring:
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/cartera_microservice
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url.defaultZone: http://192.168.1.171:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile

jwt:
  secret: electrohogarl
administration:
  microservice:
    url: http://192.168.1.192:8003/api/v1/roles