server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://192.168.1.171:3306/users_microservice
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: *

jwt:
  secret: electrohogarl